# @package data_benchmark
_target_: src.data.components.jsonl_audio_dataset.JsonlAudioDataset
dataset_name: mulab-mir__muchomusic
split: test
data_dir: ${paths.data_dir}
sampling_rate: 16000
caption_index: 1
