# @package data_member
_target_: src.data.components.jsonl_mm_detect_dataset.JsonlMMDetectDataset
dataset_name: TwinkStart__MMAU
split: v05.15.25
data_dir: ${paths.data_dir}
sampling_rate: 16000
caption_index: 1
