# @package data_member
_target_: src.data.components.jsonl_mm_detect_dataset.JsonlMMDetectDataset
dataset_name: agkphysics__AudioSet/balanced
split: train
data_dir: ${paths.data_dir}
sampling_rate: 16000
caption_index: 1
