# @package _global_

defaults:
  - _self_
  - data: clotho
  - model: audio_flamingo3
  - method: MIA_perplexity
  - logger: wandb
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

max_samples: 100
