# @package _global_

defaults:
  - _self_
  - model: audio_flamingo3
  - method: MIA_perplexity
  - data_member: clotho
  - data_non_member: clotho
  - logger: wandb
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"
tags: ["dev"]

max_member_samples: 100
max_non_member_samples: 100
batch_size: 4
