# @package data_non_member
_target_: src.data.components.jsonl_audio_dataset.JsonlAudioDataset
jsonl_path: ./data/agkphysics__AudioSet/balanced/test/metadata.jsonl
sampling_rate: 16000
label_template: "{labels}"
label_separator: ", "
