# @package data_non_member
_target_: src.data.components.audioset_dataset.AudioSetAudioTextDataset
split: test
dataset_id: agkphysics/AudioSet
config_name: balanced
sampling_rate: 16000
label_template: "{labels}"
label_separator: ", "
