# @package data_non_member
_target_: src.data.components.jsonl_audio_dataset.JsonlAudioDataset
dataset_name: lmms-lab__ClothoAQA/clotho_aqa
split: clotho_aqa_test_filtered
data_dir: ${paths.data_dir}
sampling_rate: 16000
caption_index: 1
